import type { StorefrontUiLabels } from '../types/api.js';

/** Panelden boş bırakılırsa seed / ilk kurulumda kullanılan vitrin metinleri */
export const DEFAULT_STOREFRONT_UI: StorefrontUiLabels = {
  productBadgeNew: 'Yeni',
  productBadgeFeatured: 'Öne çıkan',
  productBadgeBestSeller: 'Çok satan',
  productActionDetail: 'Detaya git',
  productActionDemo: 'Demo',
  productActionBuy: 'Satın al',
  productActionDownload: 'İndir',
  emptyProducts: 'Henüz ürün bulunmuyor.',
  emptyCategories: 'Henüz kategori bulunmuyor.',
  emptyBlog: 'Henüz blog yazısı yok.',
  notFoundMessage: 'Aradığınız sayfa bulunamadı.',
  notFoundHomeLink: 'Ana sayfaya dön',
  pageNotFoundTitle: 'Sayfa bulunamadı',
  pageNotFoundMessage: 'Bu sayfa mevcut değil veya yayından kaldırıldı.',
  pageNotFoundHomeLink: 'Ana sayfaya dön',
  blogNotFoundMessage: 'Blog yazısı bulunamadı.',
  blogNotFoundBackLink: 'Bloga dön',
  blogPostNotFoundMessage: 'Blog yazısı bulunamadı.',
  blogPostNotFoundBackLink: 'Bloga dön',
  blogIndexEmpty: 'Henüz yayınlanmış blog yazısı yok.',
  readingTimeSuffix: 'dk okuma',
  contactFormLoading: 'Form yükleniyor…',
  contactFormError: 'Mesaj gönderilemedi.',
  contactFormSubmitting: 'Gönderiliyor…',
  contactFormNotFound: 'İletişim formu yapılandırılmamış.',
  contactBackLink: 'Geri',
  formSelectPlaceholder: 'Seçin…',
  productNotFound: 'Ürün bulunamadı.',
  brandNotFound: 'Marka bulunamadı.',
  categoryNotFound: 'Kategori bulunamadı.',
  productListBackLink: 'Listeye dön',
  productBackLink: 'Geri',
  productAddToCart: 'Sepete ekle',
  productAddToCartPending: 'Ekleniyor…',
  productAddToCartError: 'Sepete eklenemedi.',
  productQuantityLabel: 'Adet',
  blogBackLink: 'Bloga dön',
  cartEmpty: 'Sepetiniz boş.',
  cartBackLink: 'Alışverişe devam',
  cartCheckoutButton: 'Ödemeye geç',
  checkoutBackLink: 'Sepete dön',
  orderNotFound: 'Sipariş bulunamadı.',
  orderSuccessHomeLink: 'Ana sayfaya dön',
  orderTrackingNotFound: 'Sipariş bulunamadı. Numara ve e-postayı kontrol edin.',
  orderTrackingNoShipment: 'Henüz kargo bilgisi yok.',
  orderTrackingBackLink: 'Geri',
  catalogSortFeatured: 'Öne çıkanlar',
  catalogSortNewest: 'En yeni',
  catalogSortPriceAsc: 'Fiyat (artan)',
  catalogSortPriceDesc: 'Fiyat (azalan)',
  catalogEmpty: 'Filtreye uygun ürün bulunamadı.',
  catalogLoading: 'Yükleniyor…',
  catalogResultsSuffix: 'sonuç',
  cartQuantityLabel: 'Adet',
  cartRemoveLabel: 'Kaldır',
  cartSummaryTitle: 'Özet',
  cartSubtotal: 'Ara toplam',
  cartTax: 'KDV',
  cartTotal: 'Toplam',
  checkoutContactTitle: 'İletişim bilgileri',
  checkoutNameLabel: 'Ad Soyad',
  checkoutEmailLabel: 'E-posta',
  checkoutPhoneLabel: 'Telefon',
  checkoutNoteLabel: 'Sipariş notu (opsiyonel)',
  checkoutPaymentTitle: 'Ödeme yöntemi',
  checkoutNoPaymentMethods:
    'Şu anda aktif ödeme yöntemi yok. Lütfen daha sonra tekrar deneyin.',
  checkoutTestMode: 'Test modu',
  checkoutBankAccountsTitle: 'Banka hesapları',
  checkoutSubmitPending: 'Sipariş oluşturuluyor…',
  checkoutSubmit: 'Siparişi tamamla',
  checkoutOrderSummary: 'Sipariş özeti',
  checkoutCouponLabel: 'Kupon kodu',
  checkoutCouponRemove: 'Kaldır',
  checkoutCouponPlaceholder: 'KUPONKODU',
  checkoutCouponApplied: 'Kupon uygulandı.',
  checkoutCouponError: 'Kupon uygulanamadı',
  checkoutCouponApply: 'Uygula',
  checkoutSubtotal: 'Ara toplam',
  checkoutTax: 'KDV',
  checkoutDiscount: 'İndirim',
  checkoutTotal: 'Toplam',
  checkoutErrorGeneric: 'Sipariş oluşturulamadı.',
  checkoutPaymentRequired: 'Lütfen bir ödeme yöntemi seçin.',
  checkoutBankAccountCount: '{count} banka hesabı',
  orderNumberLabel: 'Sipariş numaranız:',
  orderBankTransferTitle: 'Havale / EFT bilgileri',
  orderBankTransferHint:
    'Lütfen aşağıdaki hesaplardan birine ödemenizi yapın ve açıklama kısmına sipariş numaranızı yazın.',
  orderBranchLabel: 'Şube:',
  orderTrackingTitle: 'Kargo takibi',
  orderTrackingNumberLabel: 'Takip no:',
  orderTrackShipment: 'Kargoyu takip et',
  orderSummaryTitle: 'Sipariş özeti',
  orderTotalLabel: 'Toplam:',
  orderTrackLink: 'Siparişi takip et',
  orderContinueShopping: 'Alışverişe devam',
  orderTrackingFormNumberLabel: 'Sipariş numarası',
  orderTrackingFormNumberPlaceholder: 'W20250705-1234',
  orderTrackingFormEmailLabel: 'Sipariş e-postası',
  orderTrackingFormEmailPlaceholder: 'siparis@ornek.com',
  orderTrackingFormSubmit: 'Sorgula',
  orderTrackingShipmentTitle: 'Kargo bilgisi',
  orderTrackingCarrierLabel: 'Kargo firması',
  orderTrackingNumberFieldLabel: 'Takip numarası',
  catalogFiltersTitle: 'Filtreler',
  catalogFilterButton: 'Filtrele',
  catalogGridView: 'Izgara görünüm',
  catalogListView: 'Liste görünüm',
  catalogPrev: 'Önceki',
  catalogNext: 'Sonraki',
  catalogCloseFilters: 'Filtreleri kapat',
  catalogShowResults: 'Sonuçları göster',
  catalogSearchLabel: 'Ara',
  catalogSearchPlaceholder: 'Ürün ara…',
  catalogCategoryLabel: 'Kategori',
  catalogAllOption: 'Tümü',
  catalogBrandLabel: 'Marka',
  catalogPriceRangeLabel: 'Fiyat aralığı',
  catalogPriceMin: 'Min',
  catalogPriceMax: 'Max',
  catalogProductCountSuffix: '{count} ürün',
  productAttributesTitle: 'Ürün özellikleri',
  productVariantOutOfStock: 'Seçilen varyant stokta yok.',
  productVariantStock: 'Stok: {qty}',
  productVariantUnavailable: 'Bu kombinasyon mevcut değil.',
  cartAddedTitle: 'Sepete eklendi',
  cartAddedQuantity: '{qty} adet ·',
  cartAddedTotal: 'Sepetinizde toplam {count} ürün var.',
  cartAddedGoToCart: 'Sepete git',
  cartAddedContinue: 'Alışverişe devam',
  reviewsTitle: 'Müşteri yorumları',
  reviewsCount: '{count} yorum',
  reviewsEmpty: 'Henüz onaylı yorum yok.',
  reviewsLoading: 'Yorumlar yükleniyor…',
  reviewsStoreReply: 'Mağaza cevabı',
  reviewsPrev: 'Önceki',
  reviewsNext: 'Sonraki',
  reviewsWriteTitle: 'Yorum yaz',
  reviewsModerationNote:
    'Yorumunuz onaylandıktan sonra yayınlanacaktır.',
  reviewsThankYou: 'Teşekkürler! Yorumunuz incelenmek üzere alındı.',
  reviewsRatingLabel: 'Puanınız',
  reviewsNameLabel: 'Adınız',
  reviewsEmailLabel: 'E-posta',
  reviewsTitleLabel: 'Başlık (isteğe bağlı)',
  reviewsCommentLabel: 'Yorumunuz',
  reviewsSubmitPending: 'Gönderiliyor…',
  reviewsSubmit: 'Yorumu gönder',
  reviewsSubmitError: 'Yorum gönderilemedi',
};
